// This file is generated by Slice Machine. Update with care!

import Credits from './Credits';
import Images from './Images';
import Text from './Text';
import Video from './Video';

export {
	Credits,
	Images,
	Text,
	Video,
};

export const components = {
	credits: Credits,
	images: Images,
	text: Text,
	video: Video,
};
